### ISSUE TITLE
I follow "sh script/install.sh", My torch is 1.12.1+cu116. But I face this problem. Can you tell me how to solve it?

### ISSUE THREAD

**Issue by Jamie-Cheung** [ximinng/SVGDreamer#12]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 1.12.1+cu116)
    Python  3.9.19 (you have 3.9.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 198, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator aten::lift_fresh

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/disk1/zzj/AAAI2025-svg/SVGDreamer-main/svgdreamer.py", line 17, in <module>
    from svgdreamer.pipelines.SVGDreamer_pipeline import SVGDreamerPipeline
  File "/home/disk1/zzj/AAAI2025-svg/SVGDreamer-main/svgdreamer/pipelines/SVGDreamer_pipeline.py", line 23, in <module>
    from svgdreamer.painter import (CompPainter, CompPainterOptimizer, xing_loss_fn, Painter, PainterOptimizer,
  File "/home/disk1/zzj/AAAI2025-svg/SVGDreamer-main/svgdreamer/painter/__init__.py", line 9, in <module>
    from .VPSD_pipeline import VectorizedParticleSDSPipeline
  File "/home/disk1/zzj/AAAI2025-svg/SVGDreamer-main/svgdreamer/painter/VPSD_pipeline.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, UNet2DConditionModel
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/pipelines/__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/pipelines/auto_pipeline.py", line 20, in <module>
    from .controlnet import (
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/pipelines/controlnet/__init__.py", line 15, in <module>
    from .multicontrolnet import MultiControlNetModel
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/pipelines/controlnet/multicontrolnet.py", line 7, in <module>
    from ...models.controlnet import ControlNetModel, ControlNetOutput
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/models/__init__.py", line 19, in <module>
    from .adapter import MultiAdapter, T2IAdapter
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/models/adapter.py", line 22, in <module>
    from .resnet import Downsample2D
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/models/resnet.py", line 24, in <module>
    from .attention import AdaGroupNorm
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/models/attention.py", line 22, in <module>
    from .attention_processor import Attention
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 29, in <module>
    import xformers
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/xformers/__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/xformers/checkpoint.py", line 54, in <module>
    torch.ops.aten.lift_fresh.default,
  File "/home/zzj/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 202, in __getattr__
    raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
AttributeError: '_OpNamespace' object has no attribute 'lift_fresh'

**Comment by ximinng** [comment]
It looks like there was a problem installing XFORMERS (probably a python version issue, 3.10 is appropriate)

**Comment by Jamie-Cheung** [comment]
> It looks like there was a problem installing XFORMERS (probably a python version issue, 3.10 is appropriate)

In script/install.sh, the torch is 1.12.1. After installing it, I face the problem "AttributeError: module 'torch' has no attribute 'compiler'".  This compiler attribute should be available only for torch greater than 2.0. If I install the torch >=2.0. I will face the other problem, such as ImportError: /home/zzj/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found.  Besides, can you tell me the version of your Xformers? Because, when I install xformers, the torch will be installed.

**Comment by Jamie-Cheung** [comment]
> It looks like there was a problem installing XFORMERS (probably a python version issue, 3.10 is appropriate)

Thank you. I have solve it. The python version must be 3.10
